Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -1,70 +1,70 @@
-# Exemplo de fluxo de trabalho para construir e implantar um site Next.js nas páginas do GitHub
+# Sample workflow for building and deploying a Next.js site to GitHub Pages
 #
-# Para começar com Next.js, consulte: https://nextjs.org/docs/getting-started
+# To get started with Next.js see: https://nextjs.org/docs/getting-started
 #
-nome: Verifique a compilação do NextJs
+name: Check NextJs build
 
-sobre:
-  # Executa em pushes direcionados ao branch padrão
-  empurrar:
-    filiais: ["principal"]
+on:
+  # Runs on pushes targeting the default branch
+  push:
+    branches: ["main"]
     
-  # Executa em qualquer solicitação pull aberta ou reaberta
+  # Runs on any open or reopened pull request
   pull_request:
-    tipos: [aberto, reaberto]
+    types: [opened, reopened]
 
-  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
-  fluxo de trabalho_dispatch:
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
 
-ambiente:
+env:
   API_KEY: ${{ secrets.API_KEY }}
 
-# Define permissões do GITHUB_TOKEN para permitir a implantação nas páginas do GitHub
-permissões:
-  conteúdo: leia
-  páginas: escrever
-  token de identificação: escrever
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
-empregos:
-  # Construir trabalho
-  construir:
-    executado: ubuntu-mais recente
-    passos:
-      - nome: Check-out
-        usa: ações/checkout@v4
-      - nome: Detectar gerenciador de pacotes
+jobs:
+  # Build job
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Detect package manager
         id: detect-package-manager
-        executar: |
-          se [ -f "${{ github.workspace }}/yarn.lock" ]; então
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
             echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "comando=instalar" >> $GITHUB_OUTPUT
-            echo "corredor=fio" >> $GITHUB_OUTPUT
-            saída 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; então
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
             echo "manager=npm" >> $GITHUB_OUTPUT
             echo "command=ci" >> $GITHUB_OUTPUT
             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            saída 0
-          outro
-            echo "Não foi possível determinar o gerenciador de pacotes" >&2
-            saída 1
+            exit 0
+          else
+            echo "Unable to determine package manager" >&2
+            exit 1
           fi
-      - nome: Nó de configuração
-        usa: ações/setup-node@v3
-        com:
-          versão do nó: "20"
-          cache: ${{steps.detect-package-manager.outputs.manager }}
-      - nome: Restaurar cache
-        usa: ações/cache@v3
-        com:
-          caminho: |
-            .próximo/cache
-          # Gere um novo cache sempre que pacotes ou arquivos de origem forem alterados.
-          chave: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**. [jt]s', '**.[jt]sx') }}
-          # Se os arquivos de origem foram alterados, mas os pacotes não, reconstrua a partir de um cache anterior.
-          chaves de restauração: |
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "20"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
             ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-      - nome: Instalar dependências
-        execute: ${{steps.detect-package-manager.outputs.manager }} ${{steps.detect-package-manager.outputs.command }}
-      - nome: Construir com Next.js
-        executar: npm executar compilação
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
+        run: npm run build
